# Generated by Django 4.2 on 2023-06-13 04:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0002_subscription'),
    ]

    operations = [
        migrations.RenameField(
            model_name='package',
            old_name='create_time',
            new_name='created_time',
        ),
    ]
